teams:
  windows-gmsa-admins:
    description: Admin access to windows-gmsa repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  windows-gmsa-maintainers:
    description: Write access to windows-gmsa repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  sig-windows-samples-admins:
    description: Admin access to sig-windows-samples repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    previously:
    - sig-windows-examples-admins
  sig-windows-samples-maintainers:
    description: Write access to sig-windows-samples repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    previously:
    - sig-windows-examples-maintainers
  sig-windows-dev-tools-admins:
    description: Admin access to sig-windows-dev-tools repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    - sladyn98
    privacy: closed
  sig-windows-tools-admins:
    description: Admin access to sig-windows-tools repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  sig-windows-tools-maintainers:
    description: Write access to sig-windows-tools repo
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  windows-operational-readiness-admins:
    description: Admin access to the windows-operational-readiness repo
    members:
    - iXinqi
    - jayunit100
    - knabben
    privacy: closed
  windows-operational-readiness-maintainers:
    description: Write access to the windows-operational-readiness repo
    members:
    - iXinqi
    - jayunit100
    - knabben
    privacy: closed
  windows-testing-admins:
    description: Admin access to the windows-testing repo
    members:
    - adelina-t
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  windows-testing-maintainers:
    description: Write access to the windows-testing repo
    members:
    - adelina-t
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
