teams:
  sig-instrumentation-leads:
    description: ""
    members:
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    privacy: closed
  sig-instrumentation-approvers:
    description: ""
    members:
    - brancz
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    - RainbowMango
    - serathius
    privacy: closed
  sig-instrumentation-members:
    description: ""
    members:
    - brancz
    - CatherineF-dev
    - coffeepac
    - dashpole
    - dgrisonnet
    - dims
    - ehashman
    - erain
    - lilic
    - logicalhan
    - pohly
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - yangjunmyfm192085
    - YoyinZyc
    - yuzhiquan
    privacy: closed
  kube-state-metrics-admins:
    description: Admin access to the kube-state-metrics repo
    members:
    - logicalhan
    - ehashman
    - dashpole
    - dgrisonnet
    - fpetkovski
    - mrueg
    privacy: closed
  kube-state-metrics-maintainers:
    description: Write access to the kube-state-metrics repo
    members:
    - dgrisonnet
    - fpetkovski
    - mrueg
    privacy: closed
