teams:
  oci-proxy-admins:
    description: Admin access to kubernetes-sigs/oci-proxy
    maintainers:
    - ameukam
    members:
    - bentheelder
    - dims
    - spiffxp
    - thockin
    privacy: closed
  oci-proxy-maintainers:
    description: Write access to kubernetes-sigs/oci-proxy
    maintainers:
    - ameukam
    members:
    - bentheelder
    - dims
    - spiffxp
    - thockin
    privacy: closed
