teams:
  provider-azure:
    description: General discussion for SIG Azure
    members:
    - andyzhangx
    - brendandburns
    - craiglpeters
    - dstrebel
    - feiskyer
    - justaugustus
    - karataliu
    - khenidak
    - lachie83
    - lzhecheng
    - MartinForReal
    - nilo19
    - ritazh
    - soggiest
    privacy: closed
    previously:
    - sig-azure
