teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with
      access to publish packages (debs/rpms) on behalf of the Kubernetes
      project. This team is a notification-only group, which includes the SIG
      Release Chairs/TLs for continuity.
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    - cpanato
    - justaugustus
    - MushuEE
    - puerco
    - saschagrunert
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs and have triage access to the kubernetes/enhancements repo
    maintainers:
    - cblecker # ContribEx
    - fejta # Testing
    - mrbobbytables # ContribEx
    - nikhita # ContribEx
    - spiffxp # Testing
    members:
    - abgworrall # GCP
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alejandrox1 # Testing
    - ameukam # Release Manager Associate
    - andrewsykim # Cloud Provider
    - BenTheElder # Testing
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - chrigl # OpenStack
    - cici37 # 1.23 Release Notes Lead
    - claudiubelu # Windows
    - cpanato # Release Manager
    - craiglpeters # Azure
    - dashpole # Instrumentation
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dims # Architecture / Release
    - eddiezane # CLI
    - ehashman # Instrumentation
    - encodeflush # 1.23 CI Signal Lead
    - enj # Auth
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - gracenng # 1.23 Enhancements Shadow
    - hpandeycodeit # Usability
    - Huang-Wei # Scheduling
    - jameslaverack # 1.23 RT Lead Shadow
    - janetkuo # Apps
    - jayunit100 # Windows
    - jberkus # Release
    - jdumars # Architecture / PM
    - jeremyrickard # Release / 1.23 Emeritus Adviser
    - jhvhs # Service Catalog
    - jimangel # Docs / Release Manager Associate
    - jlbutler # 1.23 Docs Lead
    - johnbelamaric # Architecture
    - jrsapi # 1.23 RT Lead Shadow
    - jsafrane # Storage
    - jsturtevant # Windows
    - justaugustus # Release
    - justinsb # AWS / Cluster Lifecycle
    - jyotimahapatra # 1.23 Bug Triage Shadow
    - k8s-release-robot # Release
    - karenhchu # 1.23 Release Comms Lead
    - kevindelgado # 1.23 Enhancements Shadow
    - khenidak # Azure
    - KnVerey # CLI
    - kow3ns # Apps
    - lauralorenz # 1.23 Enhancements Shadow
    - lavalamp # API Machinery
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - liyinan926 # Big Data
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - marosset # Windows
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - mikedanese # Auth
    - mkorbi # Release Manager Associate / 1.23 RT Lead Shadow
    - mm4tt # Scalability
    - monzelmasry # 1.23 Lead Shadow
    - msau42 # Storage
    - mwielgus # Autoscaling
    - nannancy # 1.23 Bug Triage Shadow
    - nckturner # AWS
    - neolit123 # Cluster Lifecycle
    - NilimaC04 # 1.23 Bug Triage Shadow
    - onlydole # Release Manager Associate
    - oxddr # Scalability
    - palnabarun # Release Manager
    - parispittman # ContribEx
    - phillels # ContribEx
    - pmorie # Multicluster
    - Priyankasaggu11929 # 1.23 Enhancements Shadow
    - prydonius # Apps
    - puerco # Release Manager
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - rajakavitha1 # Usability
    - reylejano # 1.23 RT Lead
    - ritpanjw # 1.23 Bug Triage Shadow
    - saad-ali # Storage
    - salaxander # 1.23 Enhancements Lead
    - saschagrunert # Release
    - SataQiu # Cluster Lifecycle
    - seans3 # CLI
    - serathius # Instrumentation
    - sethmccombs # Release Manager Associate
    - shu-mutou # UI
    - shyamjvs # Scalability
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - supriya-premkumar # 1.23 Enhancements Shadow
    - tallclair # Auth
    - tashimi # Usability
    - thejoycekung # Release Manager Associate
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - varshaprasad96 # 1.23 Bug Triage Shadow
    - Verolop # Release Manager
    - vllry # Usability
    - voigt # 1.23 Bug Triage Lead
    - wilsonehusin # Release Manager Associate
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmudrii # Release Manager
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  publishing-bot-admins:
    description: Admin access to the publishing-bot repo
    maintainers:
    - nikhita
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    privacy: closed
    previously:
    - publishing-bot-reviewers
  publishing-bot-maintainers:
    description: Write access to the publishing-bot repo
    maintainers:
    - nikhita
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - palnabarun
    - puerco
    - saschagrunert
    - sttts
    - Verolop
    - xmudrii
    privacy: closed
  repo-infra-admins:
    description: Admin access to the repo-infra repo
    maintainers:
    - fejta
    members:
    - BenTheElder
    - clarketm
    - cpanato
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    privacy: closed
  repo-infra-maintainers:
    description: Write access to the repo-infra repo
    maintainers:
    - fejta
    members:
    - BenTheElder
    - clarketm
    - cpanato
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    - Verolop
    - xmudrii
    privacy: closed
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - spiffxp
    members:
    - alenkacz
    - BenTheElder
    - castrojo
    - cpanato # Technical Lead
    - dims
    - ixdy
    - JamesLaverack
    - jberkus
    - jdumars
    - jeefy
    - jeremyrickard # Technical Lead
    - justaugustus # Chair
    - LappleApple # Program Manager
    - liggitt
    - mariantalla
    - nikopen
    - onyiny-ang
    - palnabarun
    - puerco # Technical Lead
    - rawkode
    - reylejano
    - saschagrunert # Chair
    - savitharaghunathan
    - soggiest
    - tpepper
    privacy: closed
    teams:
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        members:
        - ameukam # Release Manager Associate
        - cpanato # subproject owner / Release Manager
        - jimangel # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - mkorbi # Release Manager Associate
        - onlydole # Release Manager Associate
        - palnabarun # Release Manager
        - puerco # subproject owner / Release Manager
        - saschagrunert # subproject owner / Release Manager
        - sethmccombs # Release Manager Associate
        - thejoycekung # Release Manager Associate
        - Verolop # Release Manager
        - wilsonehusin # Release Manager Associate
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            members:
            - cpanato
            - justaugustus
            - k8s-release-robot
            - palnabarun
            - puerco
            - saschagrunert
            - Verolop
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
      release-team:
        description: Members of the current Release Team and subproject owners.
        members:
        - AuraSinis # 1.24 Release Notes Lead
        - chrisnegus # 1.24 Docs Shadow
        - cici37 # 1.24 RT Lead Shadow
        - cpanato # subproject owner / Technical Lead
        - csantanapr # 1.24 Release Notes Shadow
        - encodeflush # 1.24 Enhancements Shadow
        - Debanitrkl # 1.24 Comms Shadow
        - didicodes # 1.24 Docs Shadow
        - DiptoChakrabarty # 1.24 Bug Triage Shadow
        - doshyt # 1.24 Bug Triage Shadow
        - gracenng # 1.24 Enhancements Lead
        - helayoty # 1.24 Bug Triage Shadow
        - jameslaverack # subproject owner (1.24 RT Lead)
        - jeremyrickard # subproject owner / Technical Lead
        - jiahuif # 1.24 Enhancements Shadow
        - jlbutler # 1.24 RT Lead Shadow
        - jrsapi # 1.24 EA
        - justaugustus # subproject owner / Chair
        - jyotimahapatra # 1.24 Bug Triage Lead
        - katcosgrove # 1.24 Release Comms Shadow
        - lauralorenz # 1.24 CI Signal Shadow
        - leonardpahlke # 1.24 CI Signal Lead
        - Lp-Francois # 1.24 Release Notes Shadow
        - mehabhalodiya # 1.24 Docs Shadow
        - mickeyboxell # 1.24 Comms Lead
        - mkorbi # 1.24 RT Lead Shadow
        - nate-double-u # 1.24 Docs Lead
        - Nivedita-coder # 1.24 CI Signal Shadow
        - onlydole # subproject owner (1.19 RT Lead)
        - palnabarun # subproject owner (1.21 RT Lead)
        - parul5sahoo # 1.24 Release Notes Shadow
        - pi-victor # 1.24 Docs Shadow
        - Priyankasaggu11929 # 1.24 Enhancements Shadow
        - puerco # subproject owner / Technical Lead
        - reylejano # subproject owner (1.23 RT Lead)
        - rhockenbury # 1.24 Enhancements Shadow
        - RinkiyaKeDad # 1.24 Release Notes Shadow
        - ritpanjw # 1.24 Bug Triage Shadow
        - s04 # 1.24 Comms Shadow
        - salaxander # 1.24 RT Lead Shadow
        - saschagrunert # subproject owner / Chair
        - savitharaghunathan # subproject owner (1.22 RT Lead)
        - shuheiktgw # 1.24 CI Signal Shadow
        - valaparthvi # 1.24 Comms Shadow
        - Verolop # Release Manager
        - voigt # 1.24 CI Signal Shadow
        - xmudrii # Release Manager
        privacy: closed
        teams:
          ci-signal:
            description: Members of the CI Signal team for the current release
              cycle.
            members:
            - calvh # 1.23 CI Signal Shadow
            - encodeflush # 1.23 CI Signal Lead
            - leonardpahlke # 1.23 CI Signal Shadow
            - rajula96reddy # 1.23 CI Signal Shadow
            - RinkiyaKeDad # 1.23 CI Signal Shadow
            - simrangupta234 # 1.23 CI Signal Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            members:
            - jameslaverack # 1.23 RT Lead Shadow
            - jeremyrickard # 1.23 Emeritus Advisor
            - jrsapi # 1.23 RT Lead Shadow
            - mkorbi # 1.23 RT Lead Shadow
            - monzelmasry # 1.23 RT Lead Shadow
            - reylejano # 1.23 RT Lead
            privacy: closed
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        privacy: closed
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - LappleApple # Program Manager
        - puerco # Technical Lead
        - saschagrunert # Chair
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - LappleApple # Program Manager
        - puerco # Technical Lead
        - saschagrunert # Chair
        privacy: closed
