teams:
  sig-service-catalog:
    description: Notifications for SIG service-catalog
    members:
    - carolynvs
    - jhvhs
    - mhbauer
    previously:
    - sig-service-catalog-misc
    privacy: closed
