name: Kubernetes Nightly
description: Org for Kubernetes publishing-bot work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- ameukam
- palnabarun
- savitharaghunathan
teams:
  bots:
    description: Bot service accounts in the kubernetes-nightly org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
